# -*- coding: utf-8 -*-
"""cycle 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R0cuFnb3DD5NqbpZkOHVgU9y9-va7QLQ
"""

import pandas as pd

list=[11,33,55,77,99]
print("orginal list;")
print(list)
print("\n after conversion")
print(pd.Series(list))

import pandas as pd
result=pd.date_range(start='05-01-2021',end='05-12-2021')
print(result)

import pandas as pd
data={'slno':[1,2,3,4],'name':['albin','ajay','bine','sam']}
df=pd.DataFrame(data)
print(df)

import pandas as pd
data=[['java','2000','200'],
      ['cpp','3000','300'],
      ['c','4000','400']]
data=pd.DataFrame(data)
print(data)

import pandas as pd
data=pd.read_csv('/content/diabetes.csv',header=None)
df=pd.DataFrame(data)
print(df)

import pandas as pd

details_1 = {
    'eid' : [1,2,3,4],
    'ename' : ['a','b','c','d'],
    'stipend':[123,131,23,434],
}

details_2 = {
    'eid' : [1,2,3,4],
    'designation' : ['aa','bb','cc','dd'],
}

df_1 = pd.DataFrame(details_1)
df_2 = pd.DataFrame(details_2)

dataframe = pd.merge(df_1, df_2, how = 'inner', on = 'eid')
print(dataframe)

